# Generated by Django 2.2.5 on 2020-05-01 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['topic_name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('journal_name', models.CharField(max_length=100)),
                ('establish_year', models.IntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='google_scholar.Topic')),
            ],
            options={
                'ordering': ['journal_name'],
                'unique_together': {('journal_name', 'establish_year')},
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('birth_year', models.IntegerField()),
                ('affiliation', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'country'],
                'unique_together': {('first_name', 'last_name', 'birth_year', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('pub_year', models.IntegerField()),
                ('pub_url', models.IntegerField(unique=True)),
                ('citations', models.IntegerField()),
                ('cited_by', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='google_scholar.Author')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='google_scholar.Journal')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='google_scholar.Topic')),
            ],
            options={
                'ordering': ['-pub_year'],
            },
        ),
    ]
