# Generated by Django 2.2.5 on 2020-05-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_scholar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='topic',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
